public interface SOLIDOpenCloseInterface {
    //Broken out from SOLIDOpenClose
    /// Original example from ChatGPT - good but we can do better
   
   // Decimal calculateDiscount(Decimal price);

    // From Coding with the Force

    /// This method allows us to get any type of object - for the first example were getting Contact Records 
    List<SObject> getRecords();
  //  List<Object> wrapRecordsForUIList(List<Sobject> sObjectRecords);


}